// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestTaskForSHIFTCFTBank.DataAccess.Postgres;

#nullable disable

namespace TestTaskForSHIFTCFTBank.DataAccess.Postgres.Migrations
{
    [DbContext(typeof(BankContext))]
    [Migration("20251214112731_BagFixWithType")]
    partial class BagFixWithType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.AccountsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acc_num")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("acc_num");

                    b.Property<int>("Client_ref")
                        .HasColumnType("integer")
                        .HasColumnName("client_ref");

                    b.Property<DateOnly?>("Close_date")
                        .HasColumnType("date")
                        .HasColumnName("close_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("Open_date")
                        .HasColumnType("date")
                        .HasColumnName("open_date");

                    b.Property<int>("Product_ref")
                        .HasColumnType("integer")
                        .HasColumnName("product_ref");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo");

                    b.HasKey("Id");

                    b.HasIndex("Client_ref");

                    b.HasIndex("Product_ref");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ClientsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("address");

                    b.Property<DateOnly>("Date_of_birth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("name");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("passport");

                    b.Property<string>("Place_of_birth")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("place_of_birth");

                    b.HasKey("Id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Begin_date")
                        .HasColumnType("date")
                        .HasColumnName("begin_date");

                    b.Property<DateOnly?>("End_date")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Tarif_ref")
                        .HasColumnType("integer")
                        .HasColumnName("tarif_ref");

                    b.HasKey("Id");

                    b.HasIndex("Tarif_ref");

                    b.ToTable("productype", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Client_ref")
                        .HasColumnType("integer")
                        .HasColumnName("client_ref");

                    b.Property<DateOnly?>("Close_date")
                        .HasColumnType("date")
                        .HasColumnName("close_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("Open_date")
                        .HasColumnType("date")
                        .HasColumnName("open_date");

                    b.Property<int>("Products_type_id")
                        .HasColumnType("integer")
                        .HasColumnName("product_type_id");

                    b.HasKey("Id");

                    b.HasIndex("Client_ref");

                    b.HasIndex("Products_type_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.RecordsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Acc_ref")
                        .HasColumnType("integer")
                        .HasColumnName("acc_ref");

                    b.Property<int>("Dt")
                        .HasColumnType("integer")
                        .HasColumnName("dt");

                    b.Property<DateOnly>("Oper_date")
                        .HasColumnType("date")
                        .HasColumnName("oper_date");

                    b.Property<decimal>("Sum")
                        .HasColumnType("numeric")
                        .HasColumnName("sum");

                    b.HasKey("Id");

                    b.HasIndex("Acc_ref");

                    b.ToTable("records", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.TarifsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tarifs", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.AccountsEntity", b =>
                {
                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ClientsEntity", "ClientsRef")
                        .WithMany("AccountsRef")
                        .HasForeignKey("Client_ref")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductsEntity", "ProductsRef")
                        .WithMany("AccountsRef")
                        .HasForeignKey("Product_ref")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientsRef");

                    b.Navigation("ProductsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductTypeEntity", b =>
                {
                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.TarifsEntity", "TarifsRef")
                        .WithMany("ProductTypesRef")
                        .HasForeignKey("Tarif_ref")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TarifsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductsEntity", b =>
                {
                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ClientsEntity", "ClientsRef")
                        .WithMany("ProductsRef")
                        .HasForeignKey("Client_ref")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductTypeEntity", "ProductsTypeRef")
                        .WithMany("ProductsRef")
                        .HasForeignKey("Products_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientsRef");

                    b.Navigation("ProductsTypeRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.RecordsEntity", b =>
                {
                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.AccountsEntity", "AccountsRef")
                        .WithMany("RecordsRef")
                        .HasForeignKey("Acc_ref")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.AccountsEntity", b =>
                {
                    b.Navigation("RecordsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ClientsEntity", b =>
                {
                    b.Navigation("AccountsRef");

                    b.Navigation("ProductsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductTypeEntity", b =>
                {
                    b.Navigation("ProductsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductsEntity", b =>
                {
                    b.Navigation("AccountsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.TarifsEntity", b =>
                {
                    b.Navigation("ProductTypesRef");
                });
#pragma warning restore 612, 618
        }
    }
}
