// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestTaskForSHIFTCFTBank.DataAccess.Postgres;

#nullable disable

namespace TestTaskForSHIFTCFTBank.DataAccess.Postgres.Migrations
{
    [DbContext(typeof(BankContext))]
    [Migration("20251213121225_UpdateName")]
    partial class UpdateName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.AccountsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acc_num")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("Client_ref")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Close_date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("Open_date")
                        .HasColumnType("date");

                    b.Property<int>("Product_ref")
                        .HasColumnType("integer");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Client_ref");

                    b.HasIndex("Product_ref");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ClientsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("Date_of_birth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Place_of_birth")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Begin_date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("End_date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Tarif_ref")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Tarif_ref");

                    b.ToTable("productype", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Client_ref")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Close_date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("Open_date")
                        .HasColumnType("date");

                    b.Property<int>("Products_type_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Client_ref");

                    b.HasIndex("Products_type_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.RecordsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Acc_ref")
                        .HasColumnType("integer");

                    b.Property<bool>("Dt")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Oper_date")
                        .HasColumnType("date");

                    b.Property<decimal>("Sum")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Acc_ref");

                    b.ToTable("records", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.TarifsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("tarifs", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.AccountsEntity", b =>
                {
                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ClientsEntity", "ClientsRef")
                        .WithMany("AccountsRef")
                        .HasForeignKey("Client_ref")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductsEntity", "ProductsRef")
                        .WithMany("AccountsRef")
                        .HasForeignKey("Product_ref")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientsRef");

                    b.Navigation("ProductsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductTypeEntity", b =>
                {
                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.TarifsEntity", "TarifsRef")
                        .WithMany("ProductTypesRef")
                        .HasForeignKey("Tarif_ref")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TarifsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductsEntity", b =>
                {
                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ClientsEntity", "ClientsRef")
                        .WithMany("ProductsRef")
                        .HasForeignKey("Client_ref")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductTypeEntity", "ProductsTypeRef")
                        .WithMany("ProductsRef")
                        .HasForeignKey("Products_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientsRef");

                    b.Navigation("ProductsTypeRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.RecordsEntity", b =>
                {
                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.AccountsEntity", "AccountsRef")
                        .WithMany("RecordsRef")
                        .HasForeignKey("Acc_ref")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.AccountsEntity", b =>
                {
                    b.Navigation("RecordsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ClientsEntity", b =>
                {
                    b.Navigation("AccountsRef");

                    b.Navigation("ProductsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductTypeEntity", b =>
                {
                    b.Navigation("ProductsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductsEntity", b =>
                {
                    b.Navigation("AccountsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.TarifsEntity", b =>
                {
                    b.Navigation("ProductTypesRef");
                });
#pragma warning restore 612, 618
        }
    }
}
