// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestTaskForSHIFTCFTBank.DataAccess.Postgres;

#nullable disable

namespace TestTaskForSHIFTCFTBank.DataAccess.Postgres.Migrations
{
    [DbContext(typeof(BankContext))]
    [Migration("20251213103838_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.AccountsEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ACC_NUM")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("CLIENT_REF")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("CLOSE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("OPEN_DATE")
                        .HasColumnType("date");

                    b.Property<int>("PRODUCT_REF")
                        .HasColumnType("integer");

                    b.Property<decimal>("SALDO")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.HasIndex("CLIENT_REF");

                    b.HasIndex("PRODUCT_REF");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ClientsEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("DATE_OF_BIRTH")
                        .HasColumnType("date");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PASSSPORT")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PLACE_OF_BIRTH")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("ID");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductTypeEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("BEGIN_DATE")
                        .HasColumnType("date");

                    b.Property<DateOnly>("END_DATE")
                        .HasColumnType("date");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TARIF_REF")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("TARIF_REF");

                    b.ToTable("productype", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductsEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CLIENT_REF")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("CLOSE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("OPEN_DATE")
                        .HasColumnType("date");

                    b.Property<int>("PRODUCTS_TYPE_ID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CLIENT_REF");

                    b.HasIndex("PRODUCTS_TYPE_ID");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.RecordsEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ACC_REF")
                        .HasColumnType("integer");

                    b.Property<bool>("DT")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("OPER_DATE")
                        .HasColumnType("date");

                    b.Property<decimal>("SUM")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.HasIndex("ACC_REF");

                    b.ToTable("records", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.TarifsEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<decimal>("COST")
                        .HasColumnType("numeric");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID");

                    b.ToTable("tarifs", (string)null);
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.AccountsEntity", b =>
                {
                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ClientsEntity", "ClientsRef")
                        .WithMany("AccountsRef")
                        .HasForeignKey("CLIENT_REF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductsEntity", "ProductsRef")
                        .WithMany("AccountsRef")
                        .HasForeignKey("PRODUCT_REF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientsRef");

                    b.Navigation("ProductsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductTypeEntity", b =>
                {
                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.TarifsEntity", "TarifsRef")
                        .WithMany("ProductTypesRef")
                        .HasForeignKey("TARIF_REF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TarifsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductsEntity", b =>
                {
                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ClientsEntity", "ClientsRef")
                        .WithMany("ProductsRef")
                        .HasForeignKey("CLIENT_REF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductTypeEntity", "ProductsTypeRef")
                        .WithMany("ProductsRef")
                        .HasForeignKey("PRODUCTS_TYPE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientsRef");

                    b.Navigation("ProductsTypeRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.RecordsEntity", b =>
                {
                    b.HasOne("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.AccountsEntity", "AccountsRef")
                        .WithMany("RecordsRef")
                        .HasForeignKey("ACC_REF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.AccountsEntity", b =>
                {
                    b.Navigation("RecordsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ClientsEntity", b =>
                {
                    b.Navigation("AccountsRef");

                    b.Navigation("ProductsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductTypeEntity", b =>
                {
                    b.Navigation("ProductsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.ProductsEntity", b =>
                {
                    b.Navigation("AccountsRef");
                });

            modelBuilder.Entity("TestTaskForSHIFTCFTBank.DataAccess.Postgres.Models.TarifsEntity", b =>
                {
                    b.Navigation("ProductTypesRef");
                });
#pragma warning restore 612, 618
        }
    }
}
